baseurl = "/"
languageCode = "en-us"
title = "Xianming Dou's blog"
theme = "hyde"
paginate = "8" # Number of posts per page
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Xianming Dou"
  bio = "Code player, normally on PostgreSQL. Interested in Computing/Database/Bigdata/Storage/Transaction."
  avatar = "img/avatar.png"

[Params]
  subtitle = "" # Subtitle of your site. Used in site header
  description = "Personal blogs by Xianming Dou " # Site description. Used in meta description
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  homeLayout = "content + sidebar" # Configure home page layout
  listLayout = "content + sidebar" # Configure layout for list pages
  singleLayout = "content + sidebar" # Configure layout for single pages
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.widgets]
  search = true # Enable "Search" widget
  recent_articles = true # Enable "Recent articles" widget
  recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

  # Enable "Social" widget, if any of "social_*" set a value
  social_linkedin = "xianming-dou"
  social_github = "godouxm"
  social_facebook = "xianming.dou"
  social_email = "godouxm@gmail.com"
  social_twitter = "XianmingDou"


